const ActionTypes = {
    USER_SIGNIN: "USER_SIGNIN",
    USER_SIGNOUT : "USER_SIGNOUT",
    UPDATE_SELECTED : "UPDATE_SELECTED",
    HIDE_MAIN_MENU : "HIDE_MAIN_MENU",
    SHOW_MAIN_MENU : "SHOW_MAIN_MENU"
}

export default ActionTypes;